# Generated by Django 4.0.5 on 2022-06-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='qa',
            fields=[
                ('qaID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=3000)),
                ('answer', models.TextField(max_length=3000)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jeopardy.categories')),
            ],
        ),
    ]
